// <auto-generated />
using System;
using AtlantTest.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtlantTest.Migrations
{
    [DbContext(typeof(StoreApplicationContext))]
    [Migration("20231128191928_UpdateTypeOfDates")]
    partial class UpdateTypeOfDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtlantTest.DB.Entities.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfCreation")
                        .HasColumnType("date");

                    b.Property<DateTime>("DateOfRemoving")
                        .HasColumnType("date");

                    b.Property<int>("DetailCount")
                        .HasColumnType("int");

                    b.Property<string>("DetailName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomenclCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorekeeperId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorekeeperId");

                    b.ToTable("Details", (string)null);
                });

            modelBuilder.Entity("AtlantTest.DB.Entities.Storekeeper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StoreKeepers", (string)null);
                });

            modelBuilder.Entity("AtlantTest.DB.Entities.Detail", b =>
                {
                    b.HasOne("AtlantTest.DB.Entities.Storekeeper", "Storekeeper")
                        .WithMany("Details")
                        .HasForeignKey("StorekeeperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Storekeeper");
                });

            modelBuilder.Entity("AtlantTest.DB.Entities.Storekeeper", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
